# Generated by Django 5.0.6 on 2026-09-09 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_no', models.CharField(editable=False, max_length=10, unique=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('OTHER', 'Other')], default='CASH', max_length=10)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('DUE', 'Due')], default='PAID', max_length=10)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer')),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_cost_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.laptop')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['receipt_no'], name='sales_sale_receipt_2ce604_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='sales_sale_sale_da_2fd927_idx'),
        ),
    ]
