# Generated by Django 5.0.6 on 2026-09-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, default='', max_length=250)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'phone'], name='customers_c_name_ae0c34_idx')],
            },
        ),
    ]
