# Generated by Django 5.0.6 on 2026-09-11 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('shopkeepers', '0002_shopkeeper_reference_number_shopkeeperlaptopitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shopkeeper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='shopkeepers.shopkeeper'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('READ_ONLY', 'Read-Only User'), ('SHOPKEEPER', 'Shopkeeper (limited, own account only)')], default='READ_ONLY', max_length=20),
        ),
    ]
