# Generated by Django 5.0.6 on 2026-09-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(default='Waqare Medina Computers and Laptop', max_length=200)),
                ('address', models.CharField(default='PF Road, Waqare Medina, Mianwali, Pakistan', max_length=300)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('thank_you_message', models.CharField(blank=True, default='Thank you for your business!', max_length=200)),
                ('low_stock_alerts_enabled', models.BooleanField(default=True)),
                ('due_today_reminder_enabled', models.BooleanField(default=True)),
                ('two_day_reminder_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
