# Generated by Django 5.0.6 on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='ceo_contact_number',
            field=models.CharField(blank=True, default='03288621265', max_length=30),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='ceo_name',
            field=models.CharField(blank=True, default='Yasir', max_length=150),
        ),
    ]
