# Generated by Django 5.0.6 on 2026-09-09 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=150)),
                ('generation', models.CharField(blank=True, default='', max_length=50)),
                ('processor', models.CharField(max_length=100)),
                ('cpu_cores', models.PositiveIntegerField()),
                ('ram', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('gpu', models.CharField(blank=True, default='', max_length=100)),
                ('screen_size', models.CharField(blank=True, default='', max_length=30)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('REFURBISHED', 'Refurbished')], default='NEW', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('supplier', models.CharField(blank=True, default='', max_length=150)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty', models.CharField(blank=True, default='', max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='laptops/')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['brand', 'model_name'],
                'indexes': [models.Index(fields=['brand', 'model_name', 'generation', 'condition'], name='inventory_l_brand_ccf8ec_idx'), models.Index(fields=['serial_number'], name='inventory_l_serial__c67c77_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Adjustment'), ('ARCHIVE', 'Archive')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('reference_id', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.laptop')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
