# Generated by Django 5.0.6 on 2026-09-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='type',
            field=models.CharField(choices=[('STOCK_IN', 'Stock In'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Adjustment'), ('ARCHIVE', 'Archive'), ('SHOPKEEPER', 'Given to Shopkeeper')], max_length=20),
        ),
    ]
