# Generated by Django 5.0.6 on 2026-09-09 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        ('shopkeepers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLEARED', 'Cleared / Paid in Full')], default='ACTIVE', max_length=10)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_plans', to='customers.customer')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_plans', to='inventory.laptop')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_plans', to='sales.sale')),
                ('shopkeeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_plans', to='shopkeepers.shopkeeper')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('OTHER', 'Other')], default='CASH', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=250)),
                ('credit_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='credit.creditplan')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='creditplan',
            index=models.Index(fields=['status', 'due_date'], name='credit_cred_status_9b4d29_idx'),
        ),
    ]
