# Generated by Django 5.0.6 on 2026-09-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
        ('shopkeepers', '0003_alter_shopkeeperlaptopitem_shopkeeper_and_more'),
    ]

    operations = [
        # Legacy link only (current shopkeeper accounts no longer create
        # CreditPlan rows -- see apps.shopkeepers.models). Must not block
        # deleting a shopkeeper, so this now nulls out instead of
        # protecting.
        migrations.AlterField(
            model_name='creditplan',
            name='shopkeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_plans', to='shopkeepers.shopkeeper'),
        ),
    ]
