# Generated by Django 5.0.6 on 2026-09-11 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeepers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopkeeper',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='ShopkeeperLaptopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_reference', models.CharField(blank=True, max_length=25, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=150)),
                ('core_generation', models.CharField(blank=True, default='', max_length=50)),
                ('ram', models.CharField(blank=True, default='', max_length=50)),
                ('storage', models.CharField(blank=True, default='', max_length=50)),
                ('condition', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.CharField(blank=True, default='', max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('added_at', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shopkeeper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laptops', to='shopkeepers.shopkeeper')),
            ],
            options={
                'ordering': ['added_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShopkeeperPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('OTHER', 'Other')], default='CASH', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=250)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shopkeeper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='shopkeepers.shopkeeper')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
