# Generated by Django 5.0.6 on 2026-09-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeepers', '0002_shopkeeper_reference_number_shopkeeperlaptopitem_and_more'),
    ]

    operations = [
        # Owner request: deleting a shopkeeper account should also delete
        # every laptop/payment recorded under it, instead of being blocked.
        migrations.AlterField(
            model_name='shopkeeperlaptopitem',
            name='shopkeeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='shopkeepers.shopkeeper'),
        ),
        migrations.AlterField(
            model_name='shopkeeperpayment',
            name='shopkeeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shopkeepers.shopkeeper'),
        ),
    ]
