# Generated by Django 5.0.6 on 2026-09-12 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorymovement_type'),
        ('shopkeepers', '0003_alter_shopkeeperlaptopitem_shopkeeper_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopkeeperlaptopitem',
            name='inventory_laptop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopkeeper_items', to='inventory.laptop'),
        ),
        migrations.AddField(
            model_name='shopkeeperpayment',
            name='laptop_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_payments', to='shopkeepers.shopkeeperlaptopitem'),
        ),
        migrations.CreateModel(
            name='ShopkeeperExtraMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_reference', models.CharField(blank=True, max_length=25, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=250)),
                ('added_at', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shopkeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_money', to='shopkeepers.shopkeeper')),
            ],
            options={
                'verbose_name_plural': 'Shopkeeper extra money',
                'ordering': ['added_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='shopkeeperpayment',
            name='extra_money',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_payments', to='shopkeepers.shopkeeperextramoney'),
        ),
    ]
